#! /bin/bash

# SPDX-License-Identifier: MPL-2.0

webpavif="WEBP to AVIF"
pngavif="PNG to AVIF"
jpgjxl="JPG to JXL"
pngjxl="PNG to JXL"
jpgjxllo="JPG to JXL (Lossy)"
quit="Quit"

choices=$(gum choose --header="What are we converting today?" "$pngavif" "$webpavif" "$jpgjxl" "$pngjxl" "$jpgjxllo" "$quit")

choice="$choices"

case $choice in
"$webpavif") fpaths="./*.[Ww][Ee][Bb][Pp]" ;;
"$pngavif" | "$pngjxl") fpaths="./*.[Pp][Nn][Gg]" ;;
"$jpgjxl" | "$jpgjxllo") fpaths="./*.[Jj][Pp]*[Gg]" ;;
"$quit") exit 1 ;;
*) exit 1 ;;
esac

convrtim() {
  case $choice in
  "$webpavif") magick "$f" -quality 100 "${f%.*}.webp" ;;
  "$pngavif") magick "$f" -quality 98 "${f%.*}.avif" ;;
  "$jpgjxl") cjxl --quiet --lossless_jpeg=1 "$f" "${f%.*}.jxl" ;;
  "$pngjxl") cjxl -d 0.4 --quiet "$f" "${f%.*}.jxl" ;;
  "$jpgjxllo") cjxl --quiet -d 1.0 --lossless_jpeg=0 "$f" "${f%.*}.jxl" ;;
  esac
}

revdir() {
  mkdir _review 2>/dev/null || {
    gum log -s -t rfc822 -l error "❌Folder _review already exists, please rename or remove before continuing!"
    exit 1
  }
}

conversion() {
  for f in $fpaths; do
    if [[ -f "$f" && ! -L "$f" ]]; then
      convrtim "$f" && gum log -s -t rfc822 -l info "✨Converting...$f"
    elif [[ ! -f "$f" && ! -L "$f" ]]; then
      gum log -s -t rfc822 -l error "‼️No images were found to convert!"
      exit 1
    fi
  done
}

moveto() {
  for e in $fpaths; do
    if [[ -f "$e" && ! -L "$e" ]]; then
      mv "$e" _review && gum log -s -t rfc822 -l info "📦Moving...$e to _review"
    fi
  done
}


revdir 
conversion && gum log -s -t rfc822 -l info "✅All images converted!" 
moveto && gum log -s -t rfc822 -l info '🎉All done~!!'
