#! /bin/bash

# SPDX-License-Identifier: MPL-2.0

# Use this to optimize your existing .jpg losslessly!
# NOTE: You need the "cjxl" tool to run this!

# Test to see if we can make a "_review" folder for the output, if not then exit

mkdir _review || { echo "Folder _review already exists, please rename or remove before continuing!" >&2; exit 1; }

# Find all JPG files in current directory, use the CJXL tool to losslessly convert to JXL

for f in ./*.jp*g ; do cjxl --quiet --lossless_jpeg=1 "$f" "${f%.jp*g}.jxl" ; done

# Create directory _review and then move all JPG files into it

