#! /bin/bash

# SPDX-License-Identifier: MPL-2.0

# NOTE: This one is more for when an online service or messenger either doesn't support or display .avif files 
# I recommend moving the images in question to their own folder before running this!

# Test to see if we can make a "_review" folder for the output, if not then exit

mkdir _review || { echo "Folder _review already exists, please rename or remove before continuing!" >&2; exit 1; }

# Find all AVIF files in current directory, use magick to convert them to WEBP, exclude any symlinks

for f in ./*.[Aa][Vv][Ii][Ff] ; do
  if [[ -f "$f" && ! -h "$f" ]]; then
    magick "$f" -quality 100 "${f%.*}.webp"
  fi
done

# Find all the original .AVIFs and move them to our previously created "_review" folder if it's a file and not a symlink

for e in ./*.[Aa][Vv][Ii][Ff] ; do
  if [[ -f "$e" && ! -h "$e" ]] ; then
    mv "$e" _review
  fi
done
