#! /bin/bash

# SPDX-License-Identifier: MPL-2.0

# NOTE: I highly recommend using the script with cjxl tool instead of this one!

# NOTE: This will not only reduce quality but also resolution to reduce filesize!
# Modify "-resize" value between 80%-50% depending on amount of filesize you're trying to save.

# Test to see if we can make a "_review" folder for the output, if not then exit

mkdir _review || { echo "Folder _review already exists, please rename or remove before continuing!" >&2; exit 1; }

# Find all JPG files in current directory, use magick to compress and convert to AVIF, the test will exclude any symlinks!

for f in ./*.[Jj][Pp]*[Gg] ; do
  if [[ -f "$f" && ! -h "$f" ]]; then
    magick "$f" -resize 75% -quality 96 "${f%.*}.avif"
  fi
done

# Find all the original .JPGs and move them to our previously created "_review" folder if it's a file and not a symlink

for e in ./*.[Jj][Pp]*[Gg] ; do
  if [[ -f "$e" && ! -h "$e" ]] ; then
    mv "$e" _review
  fi
done
