#! /bin/bash

# SPDX-License-Identifier: MPL-2.0

# Test to see if we can make a "_review" folder for the output, if not then exit

mkdir _review || { echo "Folder _review already exists, please rename or remove before continuing!" >&2; exit 1; }

# Find all PNG files in current directory, use magick to compress and convert to AVIF, the test will exclude any symlinks!

for f in ./*.[Pp][Nn][Gg] ; do
  if [[ -f "$f" && ! -h "$f" ]]; then
    magick "$f" -quality 98 "${f%.*}.avif"
  fi
done

# Find all the original .PNGs and move them to our previously created "_review" folder if it's a file and not a symlink

for e in ./*.[Pp][Nn][Gg] ; do
  if [[ -f "$e" && ! -h "$e" ]] ; then
    mv "$e" _review
  fi
done
